import os
import shutil
import hashlib
import json
import datetime

WORKSPACE = "C:/Users/singh/OneDrive/Documents/latent_planning"
ARCHIVE_DIR = os.path.join(WORKSPACE, "research_archive")
DOWNLOADS = "C:/Users/singh/Downloads"

EXPERIMENTS = {
    "qwen2.5_7b_countdown": os.path.join(
        WORKSPACE, "archived_baselines/qwen2.5_7b_countdown"
    ),
    "mistral_7b_countdown": os.path.join(
        WORKSPACE,
        "archived_baselines/mistral_7b_countdown/reports/mistral_7b_countdown",
    ),
    "qwen2.5_7b_game24": os.path.join(
        DOWNLOADS, "qwen2.5_7b_game24_results/submission/qwen2.5_7b_game24"
    ),
    "deepseek_r1_countdown": os.path.join(
        DOWNLOADS, "deepseek_r1_countdown_results/submission/deepseek_r1_countdown"
    ),
}

SUBDIRS = [
    "experiments",
    "reports",
    "baselines",
    "kaggle_outputs",
    "zips",
    "audits",
    "figures",
    "metadata",
]


def sha256_file(filepath):
    h = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            while chunk := f.read(8192):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return None


def build_archive():
    print(f"Building archive at {ARCHIVE_DIR}...")
    if not os.path.exists(ARCHIVE_DIR):
        os.makedirs(ARCHIVE_DIR)

    for sub in SUBDIRS:
        os.makedirs(os.path.join(ARCHIVE_DIR, sub), exist_ok=True)

    manifest = []
    provenance = []
    provenance.append("# Provenance Ledger")
    provenance.append(
        "Chain of custody for critical artifacts in the latent_planning research project.\n"
    )

    # 1. Archive Experiments
    for exp_name, exp_path in EXPERIMENTS.items():
        if not os.path.exists(exp_path):
            print(f"WARNING: Source path not found: {exp_path}")
            continue

        dest_dir = os.path.join(ARCHIVE_DIR, "experiments", exp_name)
        os.makedirs(dest_dir, exist_ok=True)

        # Copy files
        for root, _, files in os.walk(exp_path):
            for file in files:
                src = os.path.join(root, file)
                rel_path = os.path.relpath(src, exp_path)
                dst = os.path.join(dest_dir, rel_path)
                os.makedirs(os.path.dirname(dst), exist_ok=True)

                # Immutable copy
                if not os.path.exists(dst):
                    shutil.copy2(src, dst)

                # Manifest
                stat = os.stat(dst)
                h = sha256_file(dst)
                manifest.append(
                    {
                        "filename": os.path.join(
                            "experiments", exp_name, rel_path
                        ).replace("\\", "/"),
                        "size_bytes": stat.st_size,
                        "sha256": h,
                        "created_at": datetime.datetime.fromtimestamp(
                            stat.st_ctime
                        ).isoformat(),
                        "modified_at": datetime.datetime.fromtimestamp(
                            stat.st_mtime
                        ).isoformat(),
                    }
                )

                # Provenance Ledger for key files
                if file in [
                    "coherence_action_depth.csv",
                    "probe_results.csv",
                    "phase_b_oracle_report.md",
                    "phase_a_report.md",
                ] or file.endswith(".png"):
                    command = f"python scripts/run_phase_a.py --domain {exp_name.split('_')[-1]} --model {exp_name}"
                    provenance.append(
                        f"### Artifact: {os.path.join(exp_name, rel_path)}"
                    )
                    provenance.append(f"- **SHA-256:** `{h}`")
                    provenance.append(f"- **Generated By:** `scripts/run_phase_a.py`")
                    provenance.append(f"- **Estimated Command:** `{command}`")
                    provenance.append(
                        f"- **Timestamp:** {datetime.datetime.fromtimestamp(stat.st_mtime).isoformat()}"
                    )
                    provenance.append("")

    # Save Manifest
    with open(os.path.join(ARCHIVE_DIR, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    # Save Provenance Ledger
    with open(os.path.join(ARCHIVE_DIR, "PROVENANCE_LEDGER.md"), "w") as f:
        f.write("\n".join(provenance))

    print("Archive build complete.")
    print(f"Archived {len(manifest)} files.")


if __name__ == "__main__":
    build_archive()
